version: "3"

services:
    nginx:
        image: nginx:1.23.3-alpine
        restart: always
        working_dir: /app
        volumes:
            - ./:/app
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./docker/nginx/logs/:/var/log/nginx/
        ports:
            - ${APP_EXPOSED_PORT:-0}:80
        depends_on:
            - php

    php:
        build: ./docker/php
        image: my_php
        restart: always
        working_dir: /app
        volumes:
            - ./:/app/
        depends_on:
            - mysql
            - redis

    horizon:
        image: my_php
        restart: always
        working_dir: /app
        command: ["php", "artisan", "horizon"]
        volumes:
            - ./:/app
        depends_on:
            - php

    cron:
        image: my_php
        restart: always
        working_dir: /app
        command: ["cron", "-f"]
        volumes:
            - ./:/app
        depends_on:
            - php

    mysql:
        image: mysql:8.0.31-debian
        restart: always
        environment:
            - MYSQL_DATABASE=${DB_DATABASE:-app}
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD:-password}
        ports:
            - 127.0.0.1:${MYSQL_EXPOSED_PORT:-0}:3306
        volumes:
            - ./docker/mysql:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        restart: always
        environment:
            PMA_HOST: mysql
            PMA_USER: root
            PMA_PASSWORD: ${DB_PASSWORD:-password}
        volumes:
            - ./docker/phpmyadmin:/app
        ports:
            - "88:80"

    redis:
        image: redis:7.0.7-bullseye
        restart: always
        # Uncomment to enable Redis persistent storage:
        #command: [ "redis-server", "--appendonly", "yes" ]
        #volumes:
        #- ./docker/redis/data:/data
        ports:
            - 127.0.0.1:${REDIS_EXPOSED_PORT:-0}:6379
